### ISSUE TITLE
Completing a level in Safe Mode in Megahack still counts towards the completion counter

### ISSUE THREAD

**Issue by WhitteeDaKitty** [at4pm/CompletionCounter#3]
If you complete a level with the (auto) safe mode feature in megahack, in case you were doing a noclip or botted run or something, it still increase the completion counter by 1
![image](https://github.com/user-attachments/assets/61be83cd-d831-4c11-9c15-cace88c54d82)

**Comment by at4pm** [comment]
I am aware of this issue. I do not know how to fix this as it would require knowing when safe mode is enabled across all mod menus.

**Comment by at4pm** [comment]
Fixed in v1.0.4
